// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppsQuickLook: typeof import('./../src/components/spotlight/AppsQuickLook.vue')['default']
    Draggable: typeof import('vuedraggable')['default']
    ExportData: typeof import('./../src/components/ExportData.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    HomeBody: typeof import('./../src/components/home/HomeBody.vue')['default']
    HomeLoading: typeof import('./../src/components/home/HomeLoading.vue')['default']
    HomeNavigation: typeof import('./../src/components/navigation/HomeNavigation.vue')['default']
    ListApps: typeof import('./../src/components/ListApps.vue')['default']
    PageTitle: typeof import('./../src/components/includes/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WsItem: typeof import('./../src/components/navigation/WsItem.vue')['default']
  }
}
